# Generated by Django 2.2.3 on 2019-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
