# Generated by Django 2.2.1 on 2019-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190809_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
