# Generated by Django 2.2.1 on 2019-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190810_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='c_phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='puser',
            name='p_phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
