<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-08-13 08:30
=======
# Generated by Django 2.2.4 on 2019-08-15 11:40
>>>>>>> eb3c54d9a87357c40fd3513db3e8f9bea7a3e3da

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(default='', max_length=200)),
                ('show_poster', models.ImageField(blank=True, upload_to='images/')),
                ('show_start_date', models.DateField(blank=True, null=True)),
                ('show_end_date', models.DateField(blank=True, null=True)),
                ('show_time', models.TextField(default='')),
                ('show_place', models.TextField(default='')),
                ('ticket_date_1', models.DateTimeField(blank=True, null=True)),
                ('ticket_date_2', models.DateTimeField(blank=True, null=True)),
                ('ticket_date_3', models.DateTimeField(blank=True, null=True)),
                ('ticket_date_4', models.DateTimeField(blank=True, null=True)),
                ('ticket_price_1', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_price_2', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_price_3', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_price_4', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_amount_1', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_amount_2', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_amount_3', models.BigIntegerField(blank=True, default='', null=True)),
                ('ticket_amount_4', models.BigIntegerField(blank=True, default='', null=True)),
                ('bankname', models.CharField(default='', max_length=200)),
                ('account', models.BigIntegerField(default='')),
                ('opendate', models.DateField(blank=True, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
                ('canceldate', models.DateField(blank=True, null=True)),
                ('show_info_text', models.TextField(default='')),
                ('show_info_image', models.ImageField(blank=True, upload_to='images/')),
                ('post_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default='1')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
