# Generated by Django 2.2.3 on 2019-08-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(default='', max_length=200)),
                ('show_poster', models.ImageField(blank=True, upload_to='images/')),
                ('show_date', models.DateField(blank=True, null=True)),
                ('show_time', models.TextField(default='')),
                ('show_place', models.TextField(default='')),
                ('ticket_date', models.TextField(default='')),
                ('ticket_price', models.BigIntegerField(default='')),
                ('ticket_amount', models.BigIntegerField(default='')),
                ('bankname', models.CharField(default='', max_length=200)),
                ('account', models.BigIntegerField(default='')),
                ('opendate', models.DateField(blank=True, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
                ('canceldate', models.DateField(blank=True, null=True)),
                ('show_info_text', models.TextField(default='')),
                ('show_info_image', models.ImageField(blank=True, upload_to='images/')),
                ('post_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
