# Generated by Django 2.2.4 on 2019-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show_info_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
