# Generated by Django 2.2.3 on 2019-07-18 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 7, 18, 3, 107839, tzinfo=utc)),
        ),
    ]
