# Generated by Django 2.2.3 on 2019-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190729_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='canceldate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='closedate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='opendate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_date',
            field=models.DateField(default=''),
        ),
    ]
