# Generated by Django 2.2.4 on 2019-08-20 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190820_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogLike',
            new_name='PostLike',
        ),
    ]
