# Generated by Django 2.2.3 on 2019-08-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_opendate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='canceldate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='closedate',
        ),
    ]
