# Generated by Django 2.2.1 on 2019-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ticket_c_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='c_ticket',
            field=models.CharField(choices=[('Post.ticket_date_1', 't1'), ('T2', 'Ticket2'), ('T3', 'Ticket3'), ('T4', 'Ticket4')], default='Post.ticket_date_1', max_length=100),
        ),
    ]
