# Generated by Django 2.2.4 on 2019-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190815_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_amount_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_amount_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_amount_3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_amount_4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_price_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_price_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_price_3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_price_4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
