# Generated by Django 2.2.3 on 2019-07-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190730_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.BigIntegerField(),
        ),
    ]
