# Generated by Django 2.2.1 on 2019-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190815_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('T1', 'Freshman'), ('T2', 'Sophomore'), ('T3', 'Junior'), ('T4', 'Senior')], default='T1', max_length=100),
        ),
    ]
