# Generated by Django 2.2.3 on 2019-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190801_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canceldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='closedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='opendate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
