# Generated by Django 2.2.1 on 2019-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket_t_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('ticket1', 'c1'), ('ticket2', 'c2'), ('ticket2', 'c3'), ('ticket2', 'c4')], default='ticket1', max_length=100),
        ),
    ]
