# Generated by Django 2.2.3 on 2019-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190730_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_price',
            field=models.IntegerField(),
        ),
    ]
