# Generated by Django 2.2.3 on 2019-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190801_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket_date',
        ),
        migrations.AddField(
            model_name='post',
            name='show_end_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='show_start_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='ticket_end_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='ticket_start_date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_info_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
