# Generated by Django 2.2.1 on 2019-08-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190814_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
