# Generated by Django 2.2.3 on 2019-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190730_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_price',
            field=models.BigIntegerField(),
        ),
    ]
