# Generated by Django 2.2.1 on 2019-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('Ticket1', 'Freshman'), ('Ticket2', 'Sophomore')], default='Ticket1', max_length=100),
        ),
    ]
