# Generated by Django 2.2.3 on 2019-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190815_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approve',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('ticket1', 'c1'), ('ticket2', 'c2'), ('ticket3', 'c3'), ('ticket4', 'c4')], default='ticket1', max_length=100),
        ),
    ]
