# Generated by Django 2.2.1 on 2019-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ticket_t_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('Ticket1', 'Post.ticket_date_1'), ('Ticket2', 'Sophomore')], default='Ticket1', max_length=100),
        ),
    ]
