# Generated by Django 2.2.3 on 2019-07-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190731_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='account',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='canceldate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='closedate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='opendate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_info_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_info_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_place',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_poster',
        ),
        migrations.RemoveField(
            model_name='post',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket_amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket_price',
        ),
    ]
