# Generated by Django 2.2.1 on 2019-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='select_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default='1'),
        ),
    ]
