# Generated by Django 2.2.1 on 2019-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190814_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('T1', 'c1'), ('Ticket2', 'Sophomore')], default='Ticket2', max_length=100),
        ),
    ]
