# Generated by Django 2.2.1 on 2019-08-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190814_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_choice',
            field=models.CharField(choices=[('Post.ticket_date_1', 'c1'), ('Ticket2', 'Sophomore')], default='Post.ticket_date_1', max_length=100),
        ),
    ]
