# Generated by Django 2.2.3 on 2019-08-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190814_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
